#!/bin/bash

# GENERAL PARAMS

#SBATCH --job-name=recent_tweets                                # job name
#SBATCH -N 1                                                    # number of nodes
#SBATCH --workdir=/home/data_shares/fugazi/tweet-collector/     # working directory
#SBATCH --time=24:00:00                                         # time limit
#SBATCH --output=sbatch_outputs/recent_tweets.%J.out   # Name of output file (%j expands to jobId)
# #SBATCH -o sbatch_outputs/recent_tweets.%J.out                # (output file)
# #SBATCH -e sbatch_outputs/recent_tweets.%J.err                # (error file)
#SBATCH --mail-type=FAIL,END                                  # send an email when the job finishes or fails

# -----------------------------------------------------------------------------------------------------------------

# COMPUTING POWER PARAMS
#SBATCH --mem=92000                                             # memory per node
#SBATCH --partition=brown                                       # brown for GPU-power
#SBATCH --cpus-per-task=8                                       # Schedule 8 cores or other amount
#SBATCH --gres=gpu                                              # Schedule a GPU, or more with gpu:2 etc

# -----------------------------------------------------------------------------------------------------------------

# outputs some specifics about host etc.
echo "User: $(whoami)"
echo "Ran on $(hostname):" # showing which node it is running on
echo "start_time: $(date)"

# -----------------------------------------------------------------------------------------------------------------

# ENV STUFF
module load Anaconda3/2021.05 # loading anaconda
# sourcing our .bashrc
source /home/$(whoami)/.bashrc # change here your username
#activating the virtual environment
conda activate fugazi

# -----------------------------------------------------------------------------------------------------------------

# SCRIPT TO RUN
python -u fake_collector/modules/user_recent_tweets_multithread.py

echo "end_time: $(date)"