#!/bin/bash

# GENERAL PARAMS

#SBATCH --job-name=users_ideology                              # title of the job
#SBATCH -N 1                                                    # number of nodes
#SBATCH --workdir=/home/data_shares/fugazi/tweet-collector/     # working directory
#SBATCH --time=01:00:00                                         # time limit
#SBATCH --output=sbatch_outputs/users_ideology.%J.out          # Job name
# #SBATCH -o sbatch_outputs/users_ideology.%J.out              # output file
# #SBATCH -e sbatch_outputs/users_ideology.%J.err              # (error file)
#SBATCH --mail-type=FAIL,END                                    # Send an email when the job finishes or fails

# -----------------------------------------------------------------------------------------------------------------

# COMPUTING POWER PARAMS
#SBATCH --mem=92000                                             # memory per node
#SBATCH --partition=brown                                       # brown for GPU-power
#SBATCH --cpus-per-task=8                                       # Schedule 8 cores or other amount
#SBATCH --gres=gpu                                              # Schedule a GPU, or more with gpu:2 etc

# -----------------------------------------------------------------------------------------------------------------

# outputs some specifics about host etc.
echo "User running the script: $(whoami)"
echo "Running on $(hostname):" # showing which node it is running on

# -----------------------------------------------------------------------------------------------------------------

# ENV STUFF
module load Anaconda3/2021.05 # loading anaconda
# sourcing our .bashrc
source /home/$(whoami)/.bashrc # change here your username
#activating the virtual environment
conda activate fugazi

# -----------------------------------------------------------------------------------------------------------------

# SCRIPT TO RUN
python -u main.py

