#!/bin/bash

#SBATCH --job-name=myfugazijob           # Job name
#SBATCH --output=myfugazijob_report.out  # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=8                # Schedule 8 cores
#SBATCH --mem=92000                      # Memory (Megabytes)
#SBATCH --time=72:00:00                  # Run time (hh:mm:ss) - run for one hour max
#SBATCH --partition=brown                # Run on either the Red or Brown queue
#SBATCH --gres=gpu                       # Schedule a GPU, or more with gpu:2 etc
#SBATCH --mail-type=FAIL,END             # Send an email when the job finishes or fails
 
# load modules or conda environments here
# update the $CONDAENV here to match the environment created earlier
module load Anaconda3
source activate fugazi
# run the actual script
python3 fugazi.py